version: "3"
services:
  oauth:
    image: quay.io/hmpps/nomis-oauth2-server:latest
    networks:
      - hmpps
    container_name: oauth
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/auth/health"]
    environment:
      - SERVER_PORT=9090
      - SPRING_PROFILES_ACTIVE=dev

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - hmpps
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "9080:8080"
    volumes:
      - ./wiremock:/home/wiremock

networks:
  hmpps: