services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  auth-db:
    ports:
      - "5433:5432"

  hmpps-auth:
    ports:
      - "9090:9090"

  gotenberg:
    ports:
      - "9099:3000"

  localstack:
    ports:
      - "4566:4566"

  arns-api:
    ports:
      - "9080:8080"

  delius:
    ports:
      - "9081:8080"

  integrations-api:
    ports:
      - "9082:8080"

  api:
    ports:
      - "8082:8080"

  hmpps-auth-proxy:
    image: nginx:latest
    depends_on:
      - hmpps-auth
    networks:
      - hmpps
    ports:
      - "9091:9091"
    volumes:
      - ./hmpps-auth-proxy/nginx.conf:/etc/nginx/nginx.conf

  ui:
    ports:
      - "3000:3000"
    environment:
      - OAUTH_EXTERNAL_URL=${OAUTH_EXTERNAL_URL:-http://localhost:9091/auth}
      - INGRESS_URL=http://localhost:3000
    depends_on:
      - hmpps-auth-proxy
