apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  COURT_CASE_API_ID: {{ .Values.secrets.COURT_CASE_API_ID | b64enc | quote }}
  COURT_CASE_API_CLIENT_SECRET: {{ .Values.secrets.COURT_CASE_API_CLIENT_SECRET | b64enc | quote }}