spring:
  security:
    oauth2:
      client:
        registration:
          community-api-client:
            client-name: community-api-client
            client-id: hmpps-assessment-api-client-2
            client-secret: ',goZH-73xWEZ46N&PqrY03RRoba>a8$82S9vV>YjWIVCIme:24d8xAsVOnbw'
            client-authentication-method: basic
            authorization-grant-type: client_credentials
            provider: oauth-service
          audit-client:
            client-name: audit-client
            client-id: hmpps-assessment-api-client-2
            client-secret: ',goZH-73xWEZ46N&PqrY03RRoba>a8$82S9vV>YjWIVCIme:24d8xAsVOnbw'
            client-authentication-method: basic
            authorization-grant-type: client_credentials
            provider: oauth-service
        provider:
          oauth-service:
            token-uri: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token'
      resourceserver:
        jwt:
          issuer-uri: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth/issuer'
community-api:
  base-url: 'https://community-api-secure.test.delius.probation.hmpps.dsd.io/'


