server:
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  forward-headers-strategy: native
spring:
  flyway:
    enabled: true
  shutdown:
    enabled: false

