# Default values for gotenberg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: thecodingmachine/gotenberg
  port: 3000
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

