package uk.gov.justice.digital.needs.api

enum class CriminogenicNeed {

    ACCOMMODATION,
    EDUCATION_TRAINING_AND_EMPLOYABILITY,
    FINANCIAL_MANAGEMENT_AND_INCOME,
    RELATIONSHIPS,
    LIFESTYLE_AND_ASSOCIATES,
    DRUG_MISUSE,
    ALCOHOL_MISUSE,
    EMOTIONAL_WELL_BEING,
    THINKING_AND_BEHAVIOUR,
    ATTITUDES;

}
