# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/hmpps/hmpps-assessments-api
  tag: latest
  port: 8080

env:
  JAVA_OPTS: "-Xmx512m -Duser.timezone=UTC"
  OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth