---
# Per environment values which override defaults in hmpps-assessments-api/values.yaml

generic-service:
  ingress:
    host: hmpps-arn-risks-api.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    ASSESSMENT_UPDATE_API_BASE_URL: https://offender-assessments-updates.hmpps.service.justice.gov.uk
    COMMUNITY_API_BASE_URL: https://community-api.probation.service.justice.gov.uk/
    ASSESSMENT_API_BASE_URL: https://offender-prod.aks-live-1.studio-hosting.service.justice.gov.uk
    ASSESS_RISKS_AND_NEEDS_API_BASE_URL: https://assess-risks-and-needs.hmpps.service.justice.gov.uk/
    AUDIT_BASE_URL: https://audit-api.hmpps.service.justice.gov.uk
    SPRING_PROFILES_ACTIVE: "logstash,postgres,preprod"
    INGRESS_URL: "https://api.hmpps-assessments.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  enabled: true
  targetApplication: hmpps-assessments-api
  alertSeverity: hmpps-assess-risks-and-needs
