name: Main pipeline [build -> test -> deploy]

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  helm_lint:
    name: Helm lint
    strategy:
      matrix:
        environments: [ 'dev', 'preprod', 'prod' ]
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}

  build_docker:
    name: Build docker image
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      tag_latest: false
      push: false
      load: true
      docker_multiplatform: false
      upload_image_artifact: true
      image_artifact_retention_days: 2

  e2e_test:
    needs: build_docker
    uses: ./.github/workflows/e2e_test.yml
    with:
      app_version: ${{ needs.build_docker.outputs.app_version }}

  publish_docker:
    name: Publish docker image
    needs:
      - validate
      - build_docker
      - e2e_test
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_push.yml@v2
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      app_version: ${{ needs.build_docker.outputs.app_version }}
      tag_latest: true

  deploy_dev:
    name: Deploy to the development environment
    needs:
      - build_docker
      - publish_docker
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'dev'
      app_version: '${{ needs.build_docker.outputs.app_version }}'

  deploy_preprod:
    name: Deploy to the preproduction environment
    needs:
      - build_docker
      - deploy_dev
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build_docker.outputs.app_version }}'

  deploy_prod:
    name: Deploy to the production environment
    needs:
      - build_docker
      - deploy_preprod
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'prod'
      app_version: '${{ needs.build_docker.outputs.app_version }}'
